using System;
using System.Collections.Generic;

namespace eMojaLokacijaService.Common.Domain
{
	/// <summary>
	/// Request-Response messaging pattern interface.
	/// </summary>
	public interface IRequest
	{
		/// <summary>
		/// Unique identifier of the request generated by the client for each unique request.
		/// Can be used to check status of long running operations and/or any asynchronous call, logging etc.
		/// </summary>
		Guid RequestToken { get; }
	}
}
