using System;
using System.Collections.Generic;

namespace eMojaLokacijaService.Common.Domain
{
	/// <summary>
	/// Base request class for Request-Response Messaging pattern.
	/// </summary>
	[Serializable]
	public abstract class RequestBase : IRequest
	{
		/// <summary>
		/// Unique identifier of the request generated by the client for each unique request.
		/// Can be used to check status of long running operations and/or any asynchronous call, Logging etc.
		/// </summary>
		public Guid RequestToken { get; init; } = Guid.NewGuid();

		/// <summary>
		/// Unique identifier of the user trying to perform an action on the server.
		/// Used primarily for authorization purposes.
		/// </summary>
		public Guid AuthenticatedUserId { get; set; }

		/// <summary>
		/// List of active user roles (FQDN). Should be acquired from trusted source like JWT...
		/// </summary>
		public List<string> AuthenticatedUserRoles { get; set; } = new List<string>();
	}

	public static class RequestBaseExtensions
	{
		/// <summary>
		/// Recreate Irequest from source request.
		/// </summary>
		/// <param name="request"></param>
		/// <param name="sourceRequest"></param>
		/// <returns></returns>
		public static RequestBase FillFromRequest(this RequestBase request, IRequest sourceRequest)
		{
			return request;
		}
	}
}
