CREATE VIEW [Locations].[vFunLocationGeoPoint]
WITH SCHEMABINDING
AS

SELECT 
	AC.ID AS CoordinateID
,	AC.GeoPoint.STX AS LonX 
,	AC.GeoPoint.STY AS LatY
FROM 
	[Locations].[FunLocation] AS AC

GO
CREATE UNIQUE CLUSTERED INDEX [IX_CoordinateGeoPoint] ON [Locations].[vFunLocationGeoPoint]
(
	[CoordinateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

GO
CREATE NONCLUSTERED INDEX [UIX_vCoordinateGeoPoint] ON [Locations].[vFunLocationGeoPoint]
(
	[LonX] ASC,
	[LatY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

